### PR TITLE
Create new multi-arch workflow

### PR DESCRIPTION
**Pull request by nashant**
This will create arm64 images too. Have a look for nashant/kubemod-crt on dockerhub for verification (tag v1.1.4)

### CODE REVIEW

**Comment by vassilvk** [comment]
Closes #13.

**Comment by vassilvk** [comment]
Thank you @nashant!

Please remove `build/deploy-image.sh` as it is not used anymore.

**Comment by nashant** [comment]
I've removed the cleanup too, that wasn't being used either

**Comment by vassilvk** [comment]
Closes #13

**Pull request merged**
